### PR TITLE
Remove disabled nic in check

### PR DESCRIPTION
**Pull request by gtranche**
On RHEL the checks are made on all the nics, even the disabled one.
So i change the find_interfaces function to get all the interfaces and remove the ones disabled in the ifcfg config file.

### CODE REVIEW

**Review by m4ce — CHANGES_REQUESTED** [review]
Could you just make the code a bit more compact in the new logic, like:

```
        device = content[/^DEVICE=["']?([\w|\d]+)["']?/, 1]
        onboot = content[/^ONBOOT=["']?([\w|\d]+)["']?/, 1].downcase == 'yes' ? true : false
        interfaces << device unless interfaces.include?(device) or onboot == false
```

**Comment by gtranche** [comment]
Code refactored

**Comment by m4ce** [comment]
Doesn't look right, the find_interfaces() function is gone?

**Comment by gtranche** [comment]
Oops, my bad, i did something wrong with my paste.
I've pushed from git command line the file I use actually.
This on is the good one !

**Comment by m4ce** [comment]
Can you squash and make a single commit please.

**Pull request closed without merging**
